name: hello world
on: push
jobs:
  my_gha:
    runs-on: ubuntu-latest
    steps:
      - name: build steps
        run: echo Hello, ${{ vars.MY_NAME }} this is a demo build!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  test:
    runs-on: ubuntu-latest
    needs: my_gha
    steps:
      - name: Test phase
        run: echo "running test cases"

        
