name: Build & Deploy
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Build step
        run: echo "Building the application"
        
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Deploy step
        run: echo "Deploying the app"
        
