name: Context variable demo
on:
  workflow_dispatch: {}
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variable
        run: |
          echo "This workflow is triggered by ${{ github.actor }}"
          echo "The repository name is ${{ github.repository }}"

      - name: Print all variables under github
        run: echo "This is done"

      - name: Print environment variables
        run: echo "$GITHUB_SHA"
