name: If Demo
on: 
  workflow_dispatch:
    # ...existing code...
jobs:
  if-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the branch is main
        #if: github.ref == 'refs/heads/main'
        if: github.ref_name == 'main'
        run: echo "This is the main branch. Running the job."

      - name: Check if the branch is develop
        run: echo "This is the develop branch. Running the job."