name: Inputs Demo
on: 
  workflow_dispatch:
    inputs :
      enviroment: 
        description: Choose environment to deploy
        required: true
        default: dev
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
       - name: Deploy the app
         run: echo "Deploying the application to ${{ inputs.environment }}"
