name: Or condition Demo
on:
  workflow_dispatch: {}
jobs:
  orCondition-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Hari or ikeazota
        if: github.actor == 'Hari' || github.actor == 'ikeazota'
        run: echo "This job runs for either Hari or ikeazota."