name: Outputs Demo
on: push
jobs:
  outputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT

      - name: Step Two
        run: echo "The version is ${{ steps.step-one.outputs.version }}"

