name: Outputs Demo
on: workflow_dispatch
jobs:
  build:
    outputs:
      version: ${{ steps.step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Build Step 
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy the Application
        run: echo "We are deploying the app with version ${{ needs.build.outputs.version }}"

